# Generated by Django 6.0 on 2026-01-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stickynote',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
    ]
